services:
  samba-ps2:
    image: ghcr.io/servercontainers/samba:smbd-only-latest
    container_name: samba-ps2
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: 'Europe/Paris'
      SAMBA_CONF_LOG_LEVEL: 3
      AVAHI_DISABLE: 1
      WSDD2_DISABLE: 1
      GROUP_kiwi: 1500
      ACCOUNT_ps2: ${ACCOUNT_PS2}
      UID_ps2: 1600
      SAMBA_VOLUME_CONFIG_ps2: "[PS2]; path=/shares/ps2; valid users = ps2; guest ok = no; read only = yes; browseable = yes"
    volumes:
      - /mnt/Libraries/ROMs/ps2:/shares/ps2
    env_file:
      - .env
